<a href="https://colab.research.google.com/github/jeonsy22/NLP_2023/blob/main/numpy_%EC%B0%A8%EC%9B%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#차원
* 0차원: Scalar(하나의 데이터 값으로만 존재)
* 1차원: Vector(숫자들의 배열)
* 2차원: Matrix(행, 열)
* 3차원이상: Tensor(다차원배열

#[0차원]: Scalar


In [2]:
import numpy as np
a = np.array(1)
print(a)
print(a.shape)
print(a.ndim)

1
()
0


#[1차원]: Vector

In [4]:
a = np.array([1])
print(a)
print(a.shape)
print(a.ndim)

[1]
(1,)
1


In [6]:
a = np.array([1, 2])
print(a)
print(a.shape)
print(a.ndim)

[1 2]
(2,)
1


In [7]:
a = np.array([1, 2, 1, 2, 1])
print(a)
print(a.shape)
print(a.ndim)

[1 2 1 2 1]
(5,)
1


#[2차원]: Matrix(행(array), 열(columns)

In [8]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3]
(3,)
1


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


#[3차원 이상]: Tensor(다차원배열)

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
2
