<a href="https://colab.research.google.com/github/jeonsy22/NLP_2023/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
* c언어 기반이 내부반복문을 사용한 속도가 매우 빠른 라이브러리
* 다차원 배열(ndarray)을 편리하게 사용하게 해주는 파이썬 라이브러리
* python은 list만 지원할 뿐, array 기능 자체가 없다.
* numpy를 가져와서 다차원배열에 대한 논리적계산, 정렬, 통계, 시물레이션 등을 할 수 있도록 한다
* <import numpy as np> numpy를 라이브러리로부터 호출해서 'np'라고 부르기로 함.

list VS array
* array: 적은 메모리로 데이터를 빠르게 처리하고 모든 원소는 자료형을 가진다
* list: 상대적으로 속도가 매우 느리고 원소가 각각 다른 자료형을 가질 수 있다.

ndarray
* N-dimensional Array(다차원배열)
* 데이터 타입은 모두 동일
* 내부반복문을 사용함으로써 속도라 빠르다.
* 배열 간에 산술 연산이 가능

In [4]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [7]:
a = ['1', '2', '3']
b = np.array(a, dtype = int)
b

array([1, 2, 3])

In [8]:
import numpy as np
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
x = np.arange(1, 10, 2)
x

array([1, 3, 5, 7, 9])

In [10]:
y = np.arange(1, 10).reshape(3, 3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x2 = np.arange(1, 9).reshape(2, 4)
x2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
x3 = np.arange(1, 9).reshape(4, 2)
x3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
x4 = np.arange(1, 13).reshape(3, 2, 2)
x4

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])