<a href="https://colab.research.google.com/github/jeonsy22/NLP_2023/blob/main/numpy_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy 연산
연산의 기본원리
* 반복문을 사용하지 않아도 배열의 모든 원소는 반복연산이 사용된다.

In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print( a // b) # 몫
print(a % b) # 나머지

[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]
[0 0 1]
[1 2 0]


배열간의 연산

In [6]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
np.dot(data, data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])