<a href="https://colab.research.google.com/github/jeonsy22/NLP_2023/blob/main/numpy_%ED%86%B5%EA%B3%84%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy - 통계함수
* sum: 합계
* mean: 평균
* max: 가장 큰 수
* min: 가장 작은 수
* std: 표준편차
* var: 분산

In [1]:
import numpy as np
a = np.arange(10).reshape(2, 5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
x = np.sum(a)
print(x)

45


In [3]:
x = np.mean(a)
print(x)

4.5


In [5]:
a[0][0] = 10
print(a)

[[10  1  2  3  4]
 [ 5  6  7  8  9]]


In [6]:
a[1][2] = 70
print(a)

[[10  1  2  3  4]
 [ 5  6 70  8  9]]


## 실접연습 01

In [8]:
import numpy as np
점수 = np.array([80, 88, 90, 95])
단위 = np.array([3, 2, 1, 4])
총점 = sum(점수 * 단위)
평균 = 총점/sum(단위)
print(총점, 평균)

886 88.6


In [9]:
import numpy as np
점수 = np.array([80, 88, 90, 95])
단위 = np.array([3, 2, 1, 4])
총점 = sum(점수 * 단위)
평균 = np.mean(점수)
print(총점, 평균)

886 88.25


In [11]:
import numpy as np
점수 = np.array([80, 88, 90, 95])
단위 = np.array([3, 2, 1, 4])
총점 = sum(점수 * 단위)
평균 = np.mean(점수)
print('총점은:', 총점,'평균은:', 평균)

총점은: 886 평균은: 88.25


In [12]:
import numpy as np
점수 = np.array([80, 88, 90, 95])
단위 = np.array([3, 2, 1, 4])
총점 = sum(점수 * 단위)
평균 = np.mean(점수)
print('총점은:', 총점,'평균은:', 평균)
print('총점은:{}, 평균은 {}'. format(총점, 평균))

총점은: 886 평균은: 88.25
총점은:886, 평균은 88.25


         감    사과    귤    배
Kcal()   90    130    100    360

1. 하루 먹은 과일의 총 kacl는 몇인가? (total)
2. 과일 4개의 평균 kcal은 몇인가?(ave)
3. 칼로리가 가장 높은 과일은 몇 kcal인가?(H_K)
4. 칼로리가 가장 낮은 과일은 몇 kcal인가?(L_K)

In [13]:
import numpy as np
Kcal = np.array([90, 130, 100, 360])
total = np.sum(Kcal)
ave = np.mean(Kcal)
H_K = max(Kcal)
L_K = min(Kcal)
print('총 Kcal:', total)
print('평균 Kcal:', ave)
print('가장 높은 kcal:', H_K)
print('가장 낮은 Kcal:', L_K)

총 Kcal: 680
평균 Kcal: 170.0
가장 높은 kcal: 360
가장 낮은 Kcal: 90
