<a href="https://colab.research.google.com/github/jeonsy22/NLP_2023/blob/main/numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
* numpy
* The fundamental package for scientific computing with Python
* 행렬이나 다차원 배열 연산

In [5]:
#기본
data = [1, 2, 3, 4]
result = []

for i in data:
  result.append(i * 10)

print(result)

[10, 20, 30, 40]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr10 = arr * 10

print(arr10)

[10 20 30 40]


In [8]:
import numpy as np

In [9]:
data = [1, 2, 3, 4]
data * 10

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [10]:
np.array(data)

array([1, 2, 3, 4])

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
type(arr)

numpy.ndarray

In [13]:
type(data)

list

In [14]:
arr

array([1, 2, 3, 4])

In [15]:
arr * 10

array([10, 20, 30, 40])

2차원 데이터
* 리스트로 2차원 데이터를 표현하기

In [19]:
data = [[100, 80, 70, 90],
         [120, 110, 100, 110]]

In [20]:
type(data)

list

In [21]:
data[0]

[100, 80, 70, 90]

In [22]:
arr = np.array(data)

In [23]:
arr

array([[100,  80,  70,  90],
       [120, 110, 100, 110]])

In [24]:
type(arr)

numpy.ndarray

In [25]:
arr[0]

array([100,  80,  70,  90])

In [26]:
arr[1]

array([120, 110, 100, 110])

In [27]:
arr[0][0]

100